# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'all'
    open-pull-requests-limit: 5
    groups:
      angular-version-updates:
        applies-to: version-updates
        patterns:
          - '*angular*'
        update-types:
          - 'patch'
          - 'minor'
      angular-security-updates:
        applies-to: security-updates
        patterns:
          - '*angular*'
        update-types:
          - 'patch'
          - 'minor'
      production-version-updates:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - 'patch'
          - 'minor'
      production-security-updates:
        applies-to: security-updates
        dependency-type: production
        update-types:
          - 'patch'
          - 'minor'
      development-version-updates:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - 'patch'
          - 'minor'
      development-security-updates:
        applies-to: security-updates
        dependency-type: development
        update-types:
          - 'patch'
          - 'minor'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: '*angular*'
        update-types: ['version-update:semver-major']
      - dependency-name: '*eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'husky'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jsdom'
        update-types: ['version-update:semver-major']
      - dependency-name: '*lint-staged'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ng-packagr'
        update-types: ['version-update:semver-major']
      - dependency-name: '*playwright*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'prettier'
        update-types: ['version-update:semver-major']
      - dependency-name: 'rxjs'
        update-types: ['version-update:semver-major']
      - dependency-name: 'sort-package-json'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tslib'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: '*vitest*'
        update-types: ['version-update:semver-major']
